### ISSUE TITLE
How to set a main tex file?

### ISSUE THREAD

**Issue by ywpkwon** [fannheyward/coc-texlab#135]
Let's say I have
- main.tex
- chapter/a.tex
When I test `:set filetype?`, I checked that `main.tex: tex`, and `a.tex: plaintex` (which seems okay to me).

When I run `CocCommand layex.build` on `a.tex`, it is not working.
How can I let the build system know `main.tex` is the main root file?
Do I need to set `% !TeX root = main.tex` or something?

**Comment by pfoerster** [comment]
This does not seem to be an issue with `coc-texlab`. `texlab` should automatically detect your project's dependencies and figure out the main file on its own. Please consider reporting the issue at the [`texlab`](https://github.com/latex-lsp/texlab) repository instead. In that report, you should add how you include `chapter/a.tex` from the main file (e. g. `\input{chapter/a.tex}`). Do you get completion inside `chapter/a.tex`?

**Comment by ywpkwon** [comment]
Oh, I didn't know `texlab` even can do that. Good to know. I'll try to report.

> Do you get completion inside chapter/a.tex?
if completion means auto-completion like `\usep` --> `\usepackage{` and also showing available packages after the `{`, I'm getting completion.  However, isn't this irrelevant to the project structure issue, since completion can be enabled individually just by looking a file extension (filetype)?

**Comment by ywpkwon** [comment]
Hey @fannheyward, I'm getting more familiar with the `coc-texlab` (Thanks for this great plugin, btw!).
I was testing
```
    "latex.build.executable": "echo",
    "latex.build.args": ["-dummy"],
```
Then, I think `latex.Build` runs `echo -dummy main.tex`. So, I guess the last `main.tex` part comes freely (maybe determined from `texlab`?).

What if I want my custom `executable` and `args` without the automatic last `main.tex` part? For example, I may end up fully setting using `.latexmkrc`, and just want to run `latexmk` without any additional argument. I think even when I set
```
    "latex.build.executable": "latexmk",
    "latex.build.args": [""],
```
I feel like I can't remove the `main.tex` part. How about explicitly specifying the last file part as in `"latex.build.args": [..., "%p"]` or something and let user can include or not?
@pfoerster, Is this a question for `texlab`? (Sorry, I'm slightly confusing on this.)

**Comment by pfoerster** [comment]
> Is this a question for texlab?

Yes, `texlab` is responsible for providing the build functionality. I agree with you that using placeholders is a better way like we did in the forward search. Unfortunately, changing this behavior is a breaking change for some people, so you can expect it when we release `v2.0.0`.

**Comment by ywpkwon** [comment]
@pfoerster Thanks a lot!! Thanks for this great library!
