### ISSUE TITLE
Command: latex.UpdateLanguageServer not found

### ISSUE THREAD

**Issue by nicomazz** [fannheyward/coc-texlab#140]
After having installed coc-texlab, I tried to run the update language server command in this way:
- `:CocCommand`
- navigate to `latex.UpdateLanguageServer`

But I get the error: `Command: latex.UpdateLanguageServer not found`

CocInfo returns:
```
## versions

vim version: NVIM v0.4.3
node version: v13.12.0
coc.nvim version: 0.0.74-dc888b4a6e
term: xterm-256color
platform: linux

## Messages
[coc.nvim] Command: latex.UpdateLanguageServer not found
```

**Comment by fannheyward** [comment]
Open any `tex` file and try this command again. `coc-texlab` will only be activated with tex files.

**Comment by nicomazz** [comment]
I just tried with a tex file opened, and I still get the same error message.

**Comment by fannheyward** [comment]
How do you installed `coc-texlab`? What's the output `:CocList services` when you open a tex file?

**Comment by nicomazz** [comment]
It seems that retrying again `:CocUninstall coc-texlab` followed by
`:CocInstall coc-texlab` solved the problem today.
Thanks!

Il giorno gio 16 apr 2020 alle ore 11:48 Heyward Fann <
notifications@github.com> ha scritto:
