### ISSUE TITLE
How About ReInstall of TeXLab?

### ISSUE THREAD

**Issue by y1rah** [fannheyward/coc-texlab#141]
Today I've installed coc-texlab through `:CocInstall`. After server restarted, while opening a TeX file, coc-textab checked the texlab bin not exist and started downloading. Soon I found it too slow as I decide to add a proxy in `:CocConfig` doing which by canceling current editor by `Ctrl-C` with `:q`.

Edited the config with proxy, when I was restarting the service, I checked the followed information:

![Screen Shot 2020-04-13 at 5 15 25 PM](https://user-images.githubusercontent.com/30183249/79115138-a6413580-7db7-11ea-882d-31fff92a42c8.png)

which seems that coc-texlab did't delete the server file after the interruption, though I solved by `rm` that file, should it be better if an auto redownload of server or deletion after canceling could be implemented.

**Comment by doronbehar** [comment]
Somewhat related, I also think that a `texlab.path` configuration option is missing - for those who wish to use the `texlab` executable of their distro.

**Comment by doronbehar** [comment]
In the past I had to run:

```
ln -s $(which texlab) ~/.config/coc/extensions/coc-texlab-data/texlab
```

But now I see that `coc-texlab` can use `texlab` from `$PATH`. Never the less, it could be nice to have this option - for testing a new texlab release such as [v2.0.0](https://github.com/latex-lsp/texlab/releases/tag/v2.0.0) before it is installed.
```

**Comment by fannheyward** [comment]
@doronbehar  `texlab.path` added.
