### ISSUE TITLE
It seems that nothing is changed about folding

### ISSUE THREAD

**Issue by wrvsrx** [fannheyward/coc-texlab#144]
#1763 has been merged into release branch, however the problem in #142 still exists. (I have updated coc.nvim)

![image](https://user-images.githubusercontent.com/42770726/79329082-b9840a80-7f49-11ea-8ad7-3e2619ef54ce.png)

According to the commit in release brance, it seems that only version number are changed
![image](https://user-images.githubusercontent.com/42770726/79329542-91e17200-7f4a-11ea-9829-844f013ee1b7.png)

**Comment by fannheyward** [comment]
On my local tests, `call CocAction('fold')` works. Any error message output?

**Comment by wrvsrx** [comment]
![image](https://user-images.githubusercontent.com/42770726/79331282-804d9980-7f4d-11ea-98d4-78c0c050ece8.png)

Error message doesn't change. As you can see, I use the newest release.

**Comment by wrvsrx** [comment]
I test that on gvim and vim in wsl2 on my two PCs. The results are same.

**Comment by wrvsrx** [comment]
After merging commit 22e796a4d959bff53737ffbad5588e25f08cd57d into release, it works well now.
