### ISSUE TITLE
Default paramater of "latex.build.args" causes error

### ISSUE THREAD

**Issue by wrvsrx** [fannheyward/coc-texlab#145]
Tex files can't be build with default paramater.

After update on today (or yesterday?), I found that latex files can't be built with default paramater. 

The default paramater of "latex.build.args" changes from ["-pdf", "-interaction=nonstopmode", "-synctex=1"] to ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"] in this update, which makes build fail.

## Reproduce

1. create test.tex
```latex
\documentclass{article}
\begin{document}
test
\end{document}
```
2. build with default paramater of "latex.build.args"
```vim
:CocCommand latex.Build
```
3. build fails
![image](https://user-images.githubusercontent.com/42770726/79401059-9c3b5480-7fba-11ea-936d-3f5a19abf784.png)
4. change "latex.build.args" from default value now to ["-pdf", "-interaction=nonstopmode", "-synctex=1"], restart coc.nvim, build success.

**Comment by fannheyward** [comment]
Thanks for your report, I've revert this change, use `:CocUpdate` to upgrade.

The latest TexLab added file placeholder https://github.com/latex-lsp/texlab/commit/f8ddb14601217626862c36e222963761967ecad1#diff-9300feef84bdf7e5ab58b05fa4eb0794R176 and https://github.com/latex-lsp/texlab-vscode/commit/28c6e26857a3484520d15637ebc37076f65a2cfa, but not release yet.
