### ISSUE TITLE
"error: Unknown function: coc#util#valid_state" when entering window

### ISSUE THREAD

**Issue by Melkster** [fannheyward/coc-texlab#151]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-496-gd2766b06c
node version: v10.15.3
coc.nvim version: 0.0.78-f4400f58ef
term: undefined
platform: win32

## Messages
[coc.nvim] TexLab Server Started


[coc.nvim] error: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state
## Output channel: TexLab



```

## Describe the bug

The following error message is printed whenever I jump to a `*.tex` window:

```
[coc.nvim] error: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state
```

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'neoclide/coc.nvim'
call vundle#end()
let g:coc_global_extensions = ['coc-texlab']
```

- Start (neo)vim with command: `nvim -u mini.vim`
- Create a window split
- Open a `*.tex`-file that has been compiled and has a `.log`-file
- Leave and enter the file's window with the cursor
- Previously mentioned error should appear

The error seems to be related to the file's corresponding `.log`-file, because after removing it the error doesn't appear. After restoring the log file the error re-appears.

**Comment by fannheyward** [comment]
Please reinstall your coc.nvim https://github.com/neoclide/coc.nvim/issues/1982

**Comment by Melkster** [comment]
@fannheyward Thanks, that solved it!
