### ISSUE TITLE
texlab existed with code: null

### ISSUE THREAD

**Issue by XiaowenHu96** [fannheyward/coc-texlab#155]
The binary texlab comes with `:CocInstall coc-texlab` doesn't seem to work.
I have to install texlab either from a package manager or from github  and change `texlab.path` to the executable to make it work.

Reproduce & behaviour:
1. `:CocInstall coc-texlab`
2.   open a tex file and cannot trigger any expected functionality.
3. `:CocInfo` shows:
```
vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78-d5471449bf
coc.nivm directory: /home/xiaowen/.config/nvim/autoload/plugged/coc.nvim
term: xterm-256color
platform: linux

## Output channel: TexLab

## Output channel: texlab

[Error  - 11:09:59 PM] /home/xiaowen/.config/coc/extensions/coc-texlab-data/texlab exited with code: null
```

**Comment by fannheyward** [comment]
There’s no such command `CocInstall texlab`.

**Comment by XiaowenHu96** [comment]
> There’s no such command `CocInstall texlab`.

It was just a typo, fixed it. I don't really get your point.

**Comment by fannheyward** [comment]
Does `/home/xiaowen/.config/coc/extensions/coc-texlab-data/texlab --version` works? Maybe `texlab` binary is broken.

**Comment by XiaowenHu96** [comment]
The binary is indeed broken. Running it triggers a segmentation fault. 
Manually removed the directory `coc-texlab-data` and re-run `:CocInstall coc-texlab` solved this.
