### ISSUE TITLE
Completion works incorrectly in neovim

### ISSUE THREAD

**Issue by wrvsrx** [fannheyward/coc-texlab#156]
## Describe

Just see the picture, when I type "equ" in vim, "equation" lies on the top of completion windows. However, in neovim, "enumerate" is on the top.

Since I have input the first three characters of "equation", "equation" should be higher that "enumerate".

![image](https://user-images.githubusercontent.com/42770726/84011745-25fb1300-a9a9-11ea-93d2-6d13095a90d6.png)
![image](https://user-images.githubusercontent.com/42770726/84011711-18de2400-a9a9-11ea-82ef-3fc2b96b3a08.png)

## Reproduce

1. use minimal vimrc
```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
2. open "test.tex" and input as the pictures above

**Comment by eyalk5** [comment]
I think coc-vimtex is the plugin that does completion

**Comment by wrvsrx** [comment]
> I think coc-vimtex is the plugin that does completion

I don't use coc-vimtex.

**Comment by fannheyward** [comment]
Upgrade your nvim and coc.nvim to latest release and try again.
