### ISSUE TITLE
Does not format

### ISSUE THREAD

**Issue by liuhaowen478** [fannheyward/coc-texlab#166]
The format command does not do anything to the code with no error message.
I can only see the log:
```
:call CocActionAsync('formatSelected', visualmode())
```
I'm running on Ubuntu 20.04 with `texlive-full` installed.
I have `nvim v0.5.0-nightly`.

**Comment by fannheyward** [comment]
Does `:call CocAction('format')` work?

**Comment by liuhaowen478** [comment]
Yes, it does work. I'm confusion. Are those two different?

**Comment by fannheyward** [comment]
`formatSelected` needs LS support [rangeFormatting](https://microsoft.github.io/language-server-protocol/specification#textDocument_rangeFormatting), looks like TexLab doesn't support this.
