### ISSUE TITLE
Image link in completion

### ISSUE THREAD

**Issue by ludwj61** [fannheyward/coc-texlab#170]
![image](https://user-images.githubusercontent.com/42984254/95272048-65c5f000-080d-11eb-9824-35482a36e943.png)

This occurs with many of the completion options from this plugin. Is there a reason for this/a way to fix it?

---
Thank you for the plugin!

**Comment by ludwj61** [comment]
Also, is there a way to disable completion from coc-texlab completely and just keep linting and other features?

**Comment by fannheyward** [comment]
> Also, is there a way to disable completion from coc-texlab completely and just keep linting and other features?

`autocmd FileType tex let b:coc_suggest_disable = 1`
