### ISSUE TITLE
Does it support formatting?

### ISSUE THREAD

**Issue by TornaxO7** [fannheyward/coc-texlab#171]
Hello, I've got a question. If I use the `<Plug>(coc-format)` command, than it doesn't format my current LaTeX code. I've `vimtex` and `coc-vimtex` installed. Am I missing something or is this feature missing?

**Comment by fannheyward** [comment]
Does `:call CocAction('format')` work?

**Comment by TornaxO7** [comment]
No it doesn't. If you want to know how my configs actually look, here's a link to my `vimtex` settings:
https://github.com/TornaxO7/my_configs/tree/master/nvim/ftplugin/tex
And here are my `coc-settings`:
https://github.com/TornaxO7/my_configs/blob/master/nvim/coc-settings.json
https://github.com/TornaxO7/my_configs/blob/master/nvim/plugins/coc.vim

That's how it currently looks like:
![GIF](https://user-images.githubusercontent.com/50843046/96762136-97c47e00-13d9-11eb-9393-88ab68f8eb53.gif)

I expected that it adds the indentation for me automatically.

**Comment by fannheyward** [comment]
Texlab supports document formatting, https://texlab.netlify.app, but I don't think it can add indentation in your case.

**Comment by pfoerster** [comment]
`texlab` uses `latexindent` to format LaTeX documents. You can try running `latexindent` directly and see if it changes something. If yes, you can open an issue over at the `texlab` repo and collect a log file using `texlab -vvvv --log-file /some/path/texlab.log`.

**Comment by TornaxO7** [comment]
Ok, thank you guys for the responds :)
