### ISSUE TITLE
how to update form texlab standalone to coc-texlab

### ISSUE THREAD

**Issue by rudrab** [fannheyward/coc-texlab#18]
Hi,

I have this configuration with texlab standalone installed manually:
```
let g:coc_user_config = {
  'latex': {
      \       'command': '/usr/local/bin/texlab',
      \       'ignoredRootPaths':['~'],
      \       'filetypes': ['tex', 'bib', 'plaintex', 'context'],
      \     },
}
```

Now, I have installed coc-texlab using `vim-plug`, and not `cocinstall`, i.e. using:
` Plug 'fannheyward/coc-texlab'
`

So, how should I alter my configuration? and should I delete `/usr/locali/bin/texlab`?

**Comment by fannheyward** [comment]
Yes, coc-texlab will install texlab to coc storage path `~/.config/coc/extensions/coc-texlab-data`, and you can use `:CocCommand latex.UpdateLanguageServer` to upgrade it.

**Comment by rudrab** [comment]
Hi, Thanks for your reply. But I don't have any such file. The possible reason is I have installed it using `vim-plug` and not `CocInstall`. Can you kindly let me know if this is usable with `vim-plug`?

**Comment by fannheyward** [comment]
According to coc.nvim wiki, https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension, using vim-plug to install coc extensions:

`Plug 'fannheyward/coc-texlab', {'do': 'yarn install --frozen-lockfile'}`

I just tested with this setting, after `PlugInstall`, there is a message `TexLab Server is not found, downloading...`, and will install `texlab` into `~/.config/coc/extensions/coc-texlab-data/texlab`.

After installation finish, you can check with `CocList services`, you will find texlab listed.
