### ISSUE TITLE
Build directory = tex file directory?

### ISSUE THREAD

**Issue by coxackie** [fannheyward/coc-texlab#188]
Hi there, and thanks for this great extension!

 I have the problem that the build files are always dumped on the directory where I launch vim from, and not in the directory on the tex file. I have tried to set "latex.build.outputDirectory" to ".", but it does not work... Any ideas what I am doing wrong?

**Comment by Neur1n** [comment]
I think the option had been changed to `texlab.auxDirectory`. And you may need to add `-output-directory=.` to `texlab.build.args` as well. For example:

```vim
call coc#config('texlab.auxDirectory', '.')
call coc#config('texlab.build.args', ['-output-directory=.'])
``

**Comment by coxackie** [comment]
@Neur1n thanks for this - not using coc anymore, as I moved to built-in lsp, so I will be closing this.
