### ISSUE TITLE
How to use coc-texlab in WSL2? 

### ISSUE THREAD

**Issue by franknova** [fannheyward/coc-texlab#199]
I've already installed (neo)vim and coc-texlab in my WSL2.
And installed the Sumatra PDF in windows.

The coc-settings.json has added those:
```json
"latex.build.onSave": true,
"latex.forwardSearch.executable": "/mnt/d/software/SumatraPDF/SumatraPDF.exe",
"latex.forwardSearch.args": ["-reuse-instance", "%p", "-forward-search", "%f", "%l"],
```
But when I run "CocCommand latex.ForwardSearch", the SumatraPDF get the wrong path like:
```
D:\mnt\d\work\aaa.tex
```
But the real path is:
```
D:\work\aaa.tex
```
How to correct this?

**Comment by fannheyward** [comment]
Check `:h g:coc_uri_prefix_replace_patterns`, does it work?
