### ISSUE TITLE
Commands and config support

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-texlab#2]
commands:

- latex.build
- latex.forwardSearch

configs https://texlab.netlify.com/docs/reference/configuration

**Comment by fannheyward** [comment]
add `texlab.UpdateLanguageServer` 978d5d70279abf9177af2303c4a8113ed4a4e4ac

**Comment by oblitum** [comment]
[Linting on change](https://github.com/latex-lsp/texlab/issues/39) is available on [1.1.0](https://github.com/latex-lsp/texlab/releases/tag/v1.1.0). I'm currently using it with:

```
  call coc#config('latex', {
  \   'lint.onChange': v:true
  \ })
```

**Comment by oblitum** [comment]
I wonder if it's possible to have [Inverse Search](https://texlab.netlify.com/docs/installation/previewing#inverse-search-3) in NeoVim.

**Comment by oblitum** [comment]
Hmm, current best candidate for that seems something like `vim --servername foo` / `vim --servername foo --remote-send ':e .vimrc | 42<cr>'`

**Comment by fannheyward** [comment]
settings added:

```
latex.lint.onSave
latex.lint.onChange
```

**Comment by fannheyward** [comment]
Added:

```
latex.build.executable
latex.build.args
latex.build.onSave
```

**Comment by fannheyward** [comment]
`latex.build` added

**Comment by fannheyward** [comment]
`latex.ForwardSearch` command added

**Comment by oblitum** [comment]
I think it's missing a command for [latex.build.cancel](https://texlab.netlify.com/docs/reference/commands#latexbuildcancel).

**Comment by oblitum** [comment]
@fannheyward I see you added the cancel command (I didn't tried yet b/c coc didn't get any updates b/c there's no release yet). Do you think it'll be usable for cancelling a continuous build started with `:CocCommand latex.Build` when `latex.build.args` have `-pvc`? It's my main usecase.

**Comment by efoerster** [comment]
The `latex.build.cancel` is currently not implemented, see [#47](https://github.com/latex-lsp/texlab/issues/47). I will reimplement it soon.

**Comment by oblitum** [comment]
@efoerster thx for the info.

**Comment by efoerster** [comment]
The `latex.build.cancel` command is now reimplemented on the server. It works a bit different now, as we use the new proposed [progress](https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.progress.proposed.md) LSP notifications which include cancellation. For details on how to implement it client-side, you can look at the [docs](https://texlab.netlify.com/docs/reference/commands#latexbuildcancel) and the [extension source](https://github.com/latex-lsp/texlab-vscode/commit/952e8dd1040a155b1fe9f43ab3a63e12691d9249#diff-45327f86d4438556066de133327f4ca2R62).

**Comment by oblitum** [comment]
@efoerster that's nice! but I guess if it's possible it would be better to have a new release for coc-texlab to pick it when it implements the client-side

**Comment by fannheyward** [comment]
@efoerster I've already reworked the build cancel command, and I'll publish new version coc-texlab when a new version of texlab released.

**Comment by efoerster** [comment]
@fannheyward A new version of TexLab has been released 🚀

**Comment by fannheyward** [comment]
@efoerster Thanks for your work,I'll test and release ASAP.

**Comment by fannheyward** [comment]
New version of coc-texlab has been released.

**Comment by yatli** [comment]
For inverse search, how about a js based executable that talks to the main plugin via a named pipe (a unix socket)? Should be pretty straightforward to implement without all the --remote complexities
