### ISSUE TITLE
Latexmk: No file name specified, and I couldn't find any

### ISSUE THREAD

**Issue by EratosthenesTheSecond** [fannheyward/coc-texlab#200]
When I run `latex.Build`, I get this error. When I exit to the terminal and run latexmk with the necessary options and filename, it works as expected. I've tried running `latex.UpdateLanguageServer`, but it freezes at `Getting the latest version...` or at `0.13%` if it gets to downloading. As a result, building on save doesn't work. Other than `"latex.build.onSave": true`, I have no other configurations for this language server.

**Comment by fannheyward** [comment]
You can download TexLab from https://github.com/latex-lsp/texlab/releases and put it into `~/.config/coc/extensions/coc-texlab-data`.
