### ISSUE TITLE
latex.UpdateLanguageServer doesn't work

### ISSUE THREAD

**Issue by carlosala** [fannheyward/coc-texlab#214]
Hi!

The title is very clear, I tried to do a `latex.UpdateLanguageServer` and it stops at `0.03%`.
Anyone knows why happens?
Thanks!

**Comment by fannheyward** [comment]
Looks like it's a network issue, coc-textlab will download TexLab from GitHub.

**Comment by oblitum** [comment]
Every time I update, it downloads but at the end I get:

```
[coc.nvim]: UnhandledRejection: spawn ETXTBSY
Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at Object.spawn (node:child_process:609:9)
    at /home/francisco/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:55393:59
```

The newly downloaded server works ok after restarting coc.

**Comment by carlosala** [comment]
Thanks for fixing it @fannheyward :)
