### ISSUE TITLE
Is it possible to show the building status of the LaTeX project?

### ISSUE THREAD

**Issue by zhiyuanzhai** [fannheyward/coc-texlab#227]
It seems that, once LaTeX build is started, nothing will be shown on the status bar, and we have to wait until the PDF previewer refreshes itself. And it doesn't warn us if the build failed.

Some feedback through `coc.nvim` would be awesome.

**Comment by fannheyward** [comment]
When you do `latex.Build`, you will get `Build started` on your status bar, and will display something like `Build success` or `Build failed: build process xxxxx` after your build succeed or failed.

**Comment by zhiyuanzhai** [comment]
@fannheyward Thanks! But what if I prefer building on save?

**Comment by fannheyward** [comment]
Set `texlab.build.onSave` to true in your coc-settings.json.

**Comment by zhiyuanzhai** [comment]
@fannheyward But I'm not getting the feedback after these settings on save. I only get feedback with `latex.Build` command.
Here's my settings: 
```json
"latex.build.executable" : "latexmk",
"latex.build.args" : [
    "-xelatex",
    "-interaction=nonstopmode",
    "-synctex=1",
    "-pvc"
],
"latex.build.onSave" : true,
"latex.lint.onChange" : true,
"latex.forwardSearch.executable" : "open -a Skim"
```

**Comment by fannheyward** [comment]
Hello, can you get any feedback on VSCode+latex with `latex.build.onSave`?

**Comment by zhiyuanzhai** [comment]
@fannheyward I'm planning to try it in VSCode later. Before that, I would like to provide more information about my current situation with VIM.

With command `latex.Build`, I can get the feedback in the command lines:
<img width="903" alt="截屏2021-06-08 上午12 48 43" src="https://user-images.githubusercontent.com/37478391/121059221-ccb00480-c7f3-11eb-969a-f4a83065812e.png">
But with `:w` (i.e., saving the file), I can't get this feedback in the command line. After some adjustment on the status bar (I'm using lightline.vim), I can see some feedback on it:
<img width="901" alt="截屏2021-06-08 上午12 56 49" src="https://user-images.githubusercontent.com/37478391/121059787-7394a080-c7f4-11eb-99bd-b5d1e77ac22b.png">
But the feedback message never changes. It keeps telling me that it's "building" even after the build is finished already (I can see the PDF file has been refreshed). This behaviour also appears when using the command. 
Besides, when using the command, I get an extra feedback in command line.
