### ISSUE TITLE
[coc.nvim] Server TexLab failed to start: spawn ETXTBSY

### ISSUE THREAD

**Issue by LinArcX** [fannheyward/coc-texlab#24]
Hi. i have __void-linux__ and install latex like this:
https://en.wikibooks.org/wiki/LaTeX/Installation#Custom_installation_with_TeX_Live
And after that try to install `coc-texlab` via __neovim__:
`:CocInstall coc-texlab`
When i hit the enter, i see this:
> [coc.nvim] TexLab Server is not found, downloading...   

And after a while:
> [coc.nvim] Server TexLab failed to start: spawn ETXTBSY  

Every time i open an `.tex` file:
> [coc.nvim] Error output from texlab: /home/linarcx/.config/coc/extensions/coc-texlab-data/texlab exited with code: null

Tip: I also notice that it downloads a file called: `texlab` and put it in: `/home/linarcx/.config/coc/extensions/coc-texlab-data/texlab`

And this is the output of `:CocInfo`:
```
## versions

vim version: NVIM v0.3.8
node version: v11.14.0
coc.nvim version: 0.0.71-fa429d0bbc
term: xterm-kitty
platform: linux

## Messages
[coc.nvim] Error output from texlab: /home/linarcx/.config/coc/extensions/coc-texlab-data/texlab exited with code: 127
[coc.nvim] Error output from texlab: Connection to server is erroring. Shutting down server.
[coc.nvim] Error output from texlab: Connection to server is erroring. Shutting down server.
[coc.nvim] Error output from texlab: Connection to server is erroring. Shutting down server.
[coc.nvim] Error output from texlab: /home/linarcx/.config/coc/extensions/coc-texlab-data/texlab exited with code: 127
## Output channel: TexLab

[Error  - 6:14:15 PM] Connection to server is erroring. Shutting down server.
[Error  - 6:14:15 PM] Connection to server is erroring. Shutting down server.
/home/linarcx/.config/coc/extensions/coc-texlab-data/texlab: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
[Error  - 6:14:15 PM] /home/linarcx/.config/coc/extensions/coc-texlab-data/texlab exited with code: 127
```

**Comment by LinArcX** [comment]
Some people said me that i can symlink those libraries:
`sudo ln -s /usr/lib/libssl.so.47 /usr/lib/libssl.so.1.1`
But i still got another error:
`error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
Also i did same action:
`sudo ln -s /usr/lib/libcrypto.so.45 /usr/lib/libcrypto.so.1.1`
But this time i'v got bunch of other errors:
https://gist.github.com/LinArcX/edbbc6424d5e5216af203dd6a14626ea

**Comment by fannheyward** [comment]
Try to download https://github.com/latex-lsp/texlab/releases/tag/v1.2.0 linux binary, and move to `~/.config/coc/extensions/coc-texlab-data/texlab`, then open tex file in vim.

Sounds like `texlab` server failed.

**Comment by efoerster** [comment]
It seems to be related to issue [#55](https://github.com/latex-lsp/texlab/issues/55) of the server. It is resolved now, but we have not pushed a new release yet. In the meantime, you can [build it from source](https://github.com/latex-lsp/texlab#building-from-source).

**Comment by LinArcX** [comment]
I find the solution. i build texlab from source and put it's binary in
/home/linarcx/.config/coc/extensions/coc-texlab-data/_texlab
Now everything works as charm.

**Comment by fannheyward** [comment]
You don’t need to build the server every time. After texlab new version released, you can upgrade it from vim by `:CocCommand latex.UpdateLanguageServer`.
