### ISSUE TITLE
Wrong suggestions/errors when using non-standard/Unicode (`[^a-zA-Z]`) macro names

### ISSUE THREAD

**Issue by Andrew15-5** [fannheyward/coc-texlab#250]
Issue https://github.com/latex-lsp/texlab/issues/857 (https://github.com/fannheyward/coc-texlab/issues/249) has been resolved and server now provides suggestions with any macro names, hurray! But now there are some bugs with coc-texlab (I'm pretty sure). Below I paste Neovim config, LaTeX file/document and some tests. Only the 3rd test is passed because macro/command name consists of non-special characters (`[a-z]`). But of course ideally all 7 must be passed (support of 99% any name).

There are some notes:

- tests were conducted using `lualatex` command (it tolerates/supports a lot more macro names than `pdflatex`)
- if more than 1 macro has the same digit (`[0-9]`) as a 1st character, then the compiler error will occur if one of them is used and won't occur if none of them is used
- adding `{}` to the 1st argument of `\newcommand` macro (the correct form) will trigger an extension error for some Unicode macro names (I don't know what are the rules for triggering the error)
- I see that default Neovim syntax highlighting also doesn't support some macro names (probably should open an issue there too)
- **[New]** tests include prior activation of suggestions (automatically or by pressing `<C-Space>`), without it tests that require pasting from clipboard wouldn't work (see https://github.com/neoclide/coc.nvim/issues/4568)
- **[New]** if `suggest.asciiMatch` (`:CocCofig`) isn't set to `false` then tests for which you have to paste non-ASCII text from clipboard wouldn't work

<details><summary>init.vim</summary>

```vim
call plug#begin($HOME . '/.config/nvim/autoload/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'joshdick/onedark.vim'
  Plug 'tpope/vim-commentary'
call plug#end()

colorscheme onedark

" Comment lines
noremap <silent> <C-/> :Commentary<CR>
inoremap <silent> <C-/> <Esc>:Commentary<CR>

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" coc-texlab
let g:tex_flavor = 'latex'

" Select auto completion option
inoremap <silent><expr> <C-j>
  \ coc#pum#visible() ? coc#pum#next(1) :
  \ CheckBackspace() ? "\<Tab>" :
  \ coc#refresh()
inoremap <expr><C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
```

</details>

<details><summary>bug.tex</summary>

```latex
\documentclass{article}
% \newcommand{\ö}{} % No error
% \newcommand{\öö}{} % Error: Unexpected "}" (texlab 1)
% \newcommand{\ööabc}{} % Error: Unexpected "}" (texlab 1)
\newcommand\ööabc{}
\def\öabc{}
\def\123{123}
\def\abc{}
\begin{document}
\end{document}
```

</details>

<details><summary>Tests</summary>

Step 0:
`\`, `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224181824-7e05bb39-51c6-4d74-99dd-782f6085c8f4.png)

<table>
<thead>
<tr>
<th>Test #</th><th>Step 1</th><th>Step 2</th>
</tr>
</thead>
<tbody>
<tr>
<td>1🔴</td>
<td>

`1`
![image](https://user-images.githubusercontent.com/37143421/224181110-eef0f733-c087-44d4-a57d-fe2fae853062.png)
(macro `\1` is undefined, shown otherwise)
</td>
<td>

`<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181231-49af3a1d-1daa-46df-a82d-ad3f744ed8ec.png)
</td>
</tr>
<tr>
<td>2🔴</td>
<td>

`123`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181315-d04c67e7-a2a3-4fa9-a437-328b7a44171a.png)
(macro `\123` is defined, shown otherwise)
</td>
<td></td>
</tr>
<tr>
<td>3🟢</td>
<td>

`abc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181450-8d51e698-8711-49b6-9481-7e9d637af66d.png)
(macro `\abc` is defined, the same is shown)
</td>
<td></td>
</tr>
<tr>
<td>4🔴</td>
<td>

`ö`, `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224181578-ca44ec82-7a5e-4d73-b8c6-e0c801a9a81b.png)
(macro `\ö` is undefined, shown otherwise)
</td>
<td>

`<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224181609-218d22e9-150f-4377-bdaf-81156b3a761f.png)
</td>
</tr>
<tr>
<td>5🔴</td>
<td>

`öabc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224184414-0db0907b-59ef-4edc-8798-2a5d4d905007.png)
(macro `\öabc` is defined, shown otherwise)
</td>
<td></td>
</tr>
<tr>
<td>6🔴</td>
<td>

`öö`
![image](https://user-images.githubusercontent.com/37143421/224184732-badb8a47-feeb-4b30-ba4d-8e857da6b5ae.png)
(macro `\ööabc` is defined, but no suggestions are shown unless `<C-Space>` is pressed again)
</td>
<td>

`abc`, `<C-J>`
![image](https://user-images.githubusercontent.com/37143421/224184901-ab23ec91-9cd1-47b4-8fbe-af9adc799237.png)
(macro `\ööabc` is defined, shown otherwise)
</td>
</tr>
<tr>
<td>7🔴</td>
<td>

`öö`,  `<C-Space>`
![image](https://user-images.githubusercontent.com/37143421/224185116-a35d3b4b-4636-42b3-ba1c-892def7be885.png)
\*Uncommented 1 line with the extension error*
(macros `\ööabc` and `\öö` are defined, but only **word** and **not a macro** `ööabc` is suggested)
</td>
<td></td>
</tr>
</tbody>
</table>

</details>

<details><summary>\newcommand{}</summary>

Meaningless errors are shown which say that the `}` character is inserted in the unexpected/wrong place, but the syntax is correct. Maybe it's only shown when the macro's name have anything appended after the Unicode character (a hunch from just looking at the places where the errors occur).

![image](https://user-images.githubusercontent.com/37143421/224190462-2e6af06c-2ba3-4408-892b-af9218b9b29d.png)
![image](https://user-images.githubusercontent.com/37143421/224190515-5d36cf47-00c1-40da-8a97-64281a5124a4.png)

Output (from `lualatex bug.tex`):
![image](https://user-images.githubusercontent.com/37143421/224190741-8098910b-3ac1-4654-adcd-6f5ad55f59a6.png)

Source code:

```latex
\documentclass{article}
\newcommand{\ö}{ö} % No error
\newcommand{\öö}{öö} % Error: Unexpected "}" (texlab 1)
\newcommand{\ööabc}{ööabc} % Error: Unexpected "}" (texlab 1)
\renewcommand\ööabc{ööabc} % No error
\def\öabc{öabc}
\def\123{123}
\def\abc{abc}
\def\a0{a0}
\def\0a{0a}
% \def\1a{1a} % OK if no macro starting with \1 is used
\begin{document}
\ö, \öö, \ööabc, \öabc, \123, \abc, \a0, \0a
\end{document}
```

</details>

---

Updated test results (checked means no issues):

- [x] test 1 (fixed)
- [x] test 2 (fixed)
- [x] test 3 (was working)
- [x] test 4 (fixed)
- [x] test 5 (fixed)
- [x] test 6 (fixed)
- [x] test 7 (fixed)
- [x] `\newcommand{...}` (fixed)
- [x] ["ultimate" test](https://github.com/latex-lsp/texlab/issues/864#issuecomment-1464560856) (fixed)

---

**Update**: main conversation/issue is now here: https://github.com/latex-lsp/texlab/issues/864. This issue will be closed with the main issue because the issue is related to both projects.

**Comment by fannheyward** [comment]
Thank you for your report. Do you have tested with the lasted texlab with that fix patch?

**Comment by Andrew15-5** [comment]
Yes, of course. Just `git clone`, `cd`, `cargo build` and `mv texlab /path/to/bin dir/`. Works like a charm.

**Comment by Andrew15-5** [comment]
Updated the comment:

- added short descriptions of what is wrong with each test
- added description for `\newcommand{}` problem
- changed incorrect/duplicate description of the 7th test
- added plugin to easily manipulate comments

**Comment by fannheyward** [comment]
Very detailed reproduce steps, will follow up on this issue.

**Comment by pfoerster** [comment]
@fannheyward It looks like all of the tests are bugs in the server and not in `coc-texlab`.

@Andrew15-5 Can you try out the latest changes on the `texlab` master branch, please? The tests should pass now :)

**Comment by Andrew15-5** [comment]
> But now there are some bugs with coc-texlab (I'm pretty sure)

Yay, I'm glad I put this `I'm pretty sure`.

@pfoerster, let me "transfer" the issue to https://github.com/latex-lsp/texlab, and then we can talk tests. ;)
