### ISSUE TITLE
How to toggle build and build-cancel using shortcut

### ISSUE THREAD

**Issue by jkunlin** [fannheyward/coc-texlab#34]
Hi, is there any way to map the build and build-cancel commands to one keyboard shortcut such as `<leader>ll`?

**Comment by fannheyward** [comment]
Like this: `nnoremap <silent> <space>b  :exe 'CocCommand latex.Build'<CR>`

`<space>b` will run `latex.Build`

**Comment by jkunlin** [comment]
I mean using the same mapping to toggle between these two status. 
That is, if it is in the continuously build status, input `<space>b` will trigger build-cancel command. 
On the contrary, if it is in the build-cancel status, input `<space>b` will trigger continuously build command.

**Comment by fannheyward** [comment]
I just added `latex.BuildToggle` command, run `:CocUpdate` to new version and give it a try, and your feedback is welcome.

**Comment by jkunlin** [comment]
Seems not work for me. It always report "build success".
When `"latex.build.onSave": true` is set in coc-setting.json, it always in the continuously build status.
If build on save is not set, using `latex.BuildToggle` command will always build files.

**Comment by fannheyward** [comment]
You need to set `"latex.build.onSave": false` when using `latex.BuildToggle`.

**Comment by jkunlin** [comment]
if `"latex.build.onSave": false` is set, using `latex.BuildToggle` will always build the files once (not continuously build).

**Comment by oblitum** [comment]
Having a `BuildToggle` command sounds like unnecessary complexity. I think this could be configured as a mapping as originally suggested.

**Comment by fannheyward** [comment]
Agreed, `BuildToggle` is unnecessary, and will add more complexity for the build control. Has removed.

**Comment by jkunlin** [comment]
Okay, thanks anyway.
