### ISSUE TITLE
`-pv` option stops vim interface

### ISSUE THREAD

**Issue by arwtyxouymz** [fannheyward/coc-texlab#54]
#### Problem
Hi, I use `coc-texlab` but I have trouble with pdf preview.
I want to open pdf viewer automatically when build is succeeded.
So I added `-pv` option to `latex.build.args` configuration, then it came to open automatically.
But after the viewer opened, vim UI is blocked and it's impossible to edit the text.
If I closed the viewer, I can edit it.

How do I execute it in the background?

#### My Environment
OS: `Ubuntu 4.15.0-62-generic`
PDF Viewer: `evince`

**Comment by fannheyward** [comment]
Use `latex.ForwardSearch`, checkout this issue: https://github.com/latex-lsp/texlab/issues/40
